version: '3.8'

services:
  db:
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "exit 0"
    ports:
      - 3307:3306
    networks:
      - backend

  app-ws:
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:3306/bank?useSSL=false",
              "spring.datasource.username" : "billa",
              "spring.datasource.password" : "billa123",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    networks:
      - backend


networks:
  backend:
